### ISSUE TITLE
Background Music doesn't change on game launch

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1011]
For exemple in biboules and robot game, the music should be different than the main music:

```
public class BibouleGameSpecSource implements GameSpecSource {
    @Override
    public GameSpec getGameSpec() {
        return new GameSpec(
            GameSummary.builder().nameCode("Biboule").gameThumbnail("data/Thumbnails/biboules.png").category(GameCategories.Category.SELECTION)
                .backgroundMusicUrl("https://opengameart.org/sites/default/files/TalkingCuteChiptune_0.mp3").build(),
            new ShooterGameLauncher());
    }
}
```

**Comment by Tohaker** [comment]
I think I can see where this has gone wrong:

In `BackgroundMusicManager` line 130:
```
if (!folderPath.equals(Configuration.DEFAULT_VALUE_MUSIC_FOLDER)) {
            isCustomMusicSet.setValue(true);
```

but `Configuration.DEFAULT_VALUE_MUSIC_FOLDER` is always an empty String, so the game will always be using a Custom Music Set.

In `GameMenuController` line 88:
```
if (!musicManager.getIsCustomMusicSet().getValue() || musicManager.getPlaylist().isEmpty()) {
                musicManager.emptyPlaylist();
                musicManager.playMusicAlone(selectedGameSpec.getGameSummary().getBackgroundMusicUrl());
                gameContext.getMusicControl().updateMusicController();
            }
```

We can only change the music by not running a Custom Music Set, which we always are. We can't ever enter this block.

**Comment by Tohaker** [comment]
So we need to decide whether we;
a) Default the music to an internal resource (so we start with `songidea(copycat).mp3`) and keep the current setup, with some tweaks.
b) Override the playing music regardless of where the music comes from. 

My vote is for _a_, but it requires a bit more work to make happen.
