### ISSUE TITLE
Music always plays on Option menu

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1018]
Even if the music is paused on the Home menu, the music will start to play when we will go in the Option menu.

**Comment by kuhlkrein** [comment]
@Tohaker when #1013 will be merge I think it will be done easily, it should actually be due to a problem in updateMusicController, in MusicControl.java

**Comment by Tohaker** [comment]
I think I noticed this issue, shouldn't be too difficult to fix 😄
