### ISSUE TITLE
Logo 1.7

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#1028]
For now, we use logo 1.6 while it should the logo 1.7

![gazeplay-1 6](https://user-images.githubusercontent.com/23239584/72528186-bf931e00-386a-11ea-8686-3927da559cd2.png)

![gazeplay-1 7](https://user-images.githubusercontent.com/23239584/72529156-f8cc8d80-386c-11ea-8fbc-a2dd7632efdb.png)

**Comment by YannRobert** [comment]
why do you want to update an image on every version ?

the version label is already displayed in the top left corner of the application window.

also, 1.6 or 1.7 are not appropriate version labels
but 1.6.0 or 1.7.0 are valid version labels

**Comment by Tohaker** [comment]
I agree with Yann, we should have a single GazePlay logo and dynamically change the version number in the banner/top bar of the app. The users won't look for a tiny number if they're trying to work out what version they're on

**Comment by schwabdidier** [comment]
In fact, now I  understood that it was on the Website which is there in order to warn people if they use an obsolete version. That is why I need the website as mentionned in the issue #1030.

**Comment by Tohaker** [comment]
If you go to https://gazeplay.github.io/GazePlay/updates/gazeplay-1-6-1-fra/ or https://gazeplay.github.io/GazePlay/updates/gazeplay-1-6-1-eng/ you'll see the messages people were getting on the wordpress site. If you navigate to a different version, you'll get a 404 with a message saying you may need to update GazePlay
Obviously this needs updating with 1.7.0, but thats now easily done through Git

**Comment by Tohaker** [comment]
Release has come out now. Closing.
