### ISSUE TITLE
when can we run the generate installer ?

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#1031]
when can we run the generate installer ? I assume that when I call release, it put everything on the release part of git and goes to version 1.7. At the very same time, dev version also change version and become newversion-snapshot. So, I have never a version 1.7 on my computer !!! How do we manage that ?

**Comment by Tohaker** [comment]
I've set the generate installer to run automatically when doing running the Gradle release task. It will up the version number to 1.7 (or whatever you set), run the installer then up the version number for development.

If this doesn't work we can always manually change the version number in the Gradle files and do it manually, but I've set this at the end of the root `build.gradle` file.
