### ISSUE TITLE
Version 1.7.1 release

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#1038]
switch off terminal output before release

**Comment by kuhlkrein** [comment]
I tried to release and here is the error I've got:

`> Task :GazePlay:preTagCommit
Running [git, commit, -m, [Gradle Release Plugin] - pre tag commit:  '1.7.1'., -a] produced an error: []

> Task :GazePlay:createReleaseTag FAILED
Running [git, tag, -a, 1.7.1, -m, [Gradle Release Plugin] - creating tag:  '1.7.1'.] produced an error: [fatal: tag '1.7.1' already exists]

> Task :release
Release process failed, reverting back any changes made by Release Plugin.

> Task :release FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':GazePlay:createReleaseTag'.
> Duplicate tag [1.7.1] - [][fatal: tag '1.7.1' already exists
  ]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 14s
1 actionable task: 1 executed
`

**Comment by schwabdidier** [comment]
Maybe you are still on your fork

**Comment by kuhlkrein** [comment]
Even if it's the fact I removed the tag with the same name on my fork. And btw, when I'm pushing something right now I'm currently pushing it on the main repo (as you can see with last commit...)

**Comment by kuhlkrein** [comment]
I did 
>gradlew clean packageApp generateInstaller
then
>gradlew release

I also tried with graddle Idea pluggin and I had the same error

**Comment by Tohaker** [comment]
As we've now release, I'll close this
