### ISSUE TITLE
Issue when using double screen

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1064]
With the ScreenDimensionSupplier we are always taking the dimension of the Screen.getMainScreen(). But maybe the user wants to play GazePlay on another screen, then the xy position of the gaze is wrongly computed.

**Comment by kuhlkrein** [comment]
I think we have several possibility:
* keep it like this, and suppose user will play only on main screen (we are already always launching GazePlay on mainScreen) -> not so user friendly
* check to which screen the eye-tracker is linked -> ok while the user is doing the calibration BEFORE lauching gazeplay (I hope it is usually done before but idk)
* check if the screen changed when we moved the Window (what should occur only once, just after launching the app imo).

**Comment by kuhlkrein** [comment]
I think the best idea would be an appScreenProperty that could change only when the x or y property of the window change ( can be done using a listener on the window position ).
@YannRobert , @Tohaker , do you have another idea ?

**Comment by Tohaker** [comment]
This is probably a MASSIVE edge case. Considering the users we have, I doubt many of them will have two screens, and even fewer will have their eye tracker on the non-primary screen (mine is on my primary at least). 

I'd say we should set the screen based on where the eye tracker is located, and if the screen changes, turn off the eye tracking with a prompt to turn it back on manually. It may not be the most elegant solution, but I can't see this being a problem very often.

**Comment by schwabdidier** [comment]
For info, I know some institutions which use several screen

**Comment by YannRobert** [comment]
I'm interested in support for using the non main screen too.

I'll have a look at the code before giving you my thoughts

**Comment by kuhlkrein** [comment]
also linked to #624
