### ISSUE TITLE
Error on raspberry Pi on launch

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1070]
unsuppported major.minor version 55.0 when executing ./gazeplay-linux.sh

**Comment by kuhlkrein** [comment]
@YannRobert , @Tohaker any idea ?

I have 
java version "1.7.0_241"
OpenJDK Runtime Environment (IcedTea 2.6.20) (7u241-2.6.20-1~deb8u1+rpi1)
OpenJDK Zero VM (build 24.241-b01, interpreted mode)

**Comment by Tohaker** [comment]
Looks like you've answered your own question :p We only support Java 11+

**Comment by schwabdidier** [comment]
Yes, but jre is include in GazePlay now, isn't ?

**Comment by Tohaker** [comment]
JRE is only applied on Windows. The included one doesn't yet have anything for Linux or MacOS.

**Comment by kuhlkrein** [comment]
Ah ok thank you, then I have to install openjdk 11 ? I tried this afternoon but the jdk doesn't install correctly yet :)

**Comment by Tohaker** [comment]
`sudo apt-get install openjdk-11-jdk`?

**Comment by Tohaker** [comment]
I'll make some changes to the jlink plugin so we can create JREs for all platforms.

**Comment by kuhlkrein** [comment]
Yes, Actually I'm with Raspbian Jessie 8 so I'll try to update the OS and then and use openjdk 11, but I think one of the problem can also be the fact that binaries compiled on intel will not be supported on ARM architecture of the raspberry

**Comment by Tohaker** [comment]
True, it may be possible to make a custom Linux distro with OpenJDK 11 installed from a functioning binary.

**Comment by kuhlkrein** [comment]
As you said it was only a problem of JDK, I'm closing.
