### ISSUE TITLE
Robots images blend in with the background

### ISSUE THREAD

**Issue by Tohaker** [GazePlay/GazePlay#1073]
In the Robots game, it's difficult for people with visual impairments to distinguish them from the background. I suggest we have a few bright palettes or patterns on the Robots so people can see them easier.

**Comment by Tohaker** [comment]
@schwabdidier is this a reasonable enhancement? Is there a colour palette we should stick to?

**Comment by schwabdidier** [comment]
In fact, I was only planning after discussion with therapist to have a black mode without this kind of image (and white mode for other kind of problems). It is very easy to make. The white mode already exists for farm, jungle, etc.

**Comment by Tohaker** [comment]
Could you explain further? Do you mean black mode as in no background image and just a black background?

**Comment by schwabdidier** [comment]
yes exactly, in order to obtain a strong contrast.

**Comment by schwabdidier** [comment]
I open an issue about that
