### ISSUE TITLE
mode without background images and white/black background

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#1076]
**Is your feature request related to a problem? Please describe.**

For people with some eye problems, it is not easy to distinguish between background images and images 

**Describe the solution you'd like**

Two switch buttons in configuration :
   - with/without background image
   - black/white background

**Describe alternatives you've considered**

**Additional context**
no

**Comment by Tohaker** [comment]
Could there also be a global "choose each time" configuration? That way users can select each time they play a game, if they like a background and it doesn't cause them issues for that particular game? We could then store this decision per user.

**Comment by schwabdidier** [comment]
Next week we have a kind of conference with many professional @kuhlkrein and I will ask them about your suggestion.
