### ISSUE TITLE
Dist versions

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#1077]
**Is your feature request related to a problem? Please describe.**
In some institution, they are not allowed by their technical service to install programs...

**Describe the solution you'd like**
Not only providing installer but also the zip version (as previously)

**Describe alternatives you've considered**
Destroy this kind of technical services but it appears uneasy ;) 

**Additional context**
no

**Comment by YannRobert** [comment]
I think this is already in the distribution directory.
It's just not uploaded to github.

I'll show you the GazePlay S3 bucket that contains every things.

**Comment by YannRobert** [comment]
See the S3 buckets where snapshots are published, whenever there is a push on the master branch :

https://gazeplay-dist.s3.eu-west-3.amazonaws.com/

**Comment by Tohaker** [comment]
I'll check out the 1.7.1 tag, build the dist and upload it to the release, since it doesn't appear to be in S3.

**Comment by Tohaker** [comment]
Next release we'll have mulitple dists per OS, so it will be easier for others to download and use
