### ISSUE TITLE
Quick access to change dwell duration (eye fixation)

### ISSUE THREAD

**Issue by YannRobert** [GazePlay/GazePlay#1083]
**Is your feature request related to a problem? Please describe.**
Eye Fixation (dwell time) is configurable in the global configuration screen.
It's a global setting. You don't have one per game.
But it seam useful to be able to quickly change it for a particular game. And you don't want to exit the game, go to config screen, set the value, try, and repeat until you find the perfect value.

**Describe the solution you'd like**
So it would be needed to have this property configurable in the quick access panel, under the game panel. 
Placed next to the "animation speed" property slider.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by schwabdidier** [comment]
yes, why not. I don't think this kind of features have been studied yet. Why not ?

I suggest to have a slider in very same panel in order to activate or not this new duration and to save the particular behavior for each game. Maybe it should be done for other items ?

**Comment by YannRobert** [comment]
Hello @Gazeplay team
This feature is really missing, that would be nice to have it soon.

**Comment by schwabdidier** [comment]
Yes @YannRobert, we forgot it. We put it on the feature list of next version. Don't hesitate to mention any other important features.
