### ISSUE TITLE
Online Multiplayer Game

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1089]
Some people asked if we already thought about creating a game playable between several users online (or on a special network).

could be multiplayer, collaboration etc....

**Comment by Tohaker** [comment]
This looks like something we can achieve with [FXGL](https://github.com/AlmasB/FXGL) as demostrated in [this video](https://www.youtube.com/watch?v=0-xL405eNwM).

Of course, we'd need a solid idea of what games would best utilise this, and also need access to host servers. I'm pretty adept at deploying cloud infrastructure, so I could advise on the hosting side of it.

**Comment by schwabdidier** [comment]
Yes, we first need a strong idea in order to do that ! We are agree with Sebastien but we wanted to avoid to forget it :)

**Comment by YannRobert** [comment]
So many things to do before that.

Project needs to focus on adding actual value for disabled users.

Please don't fall into trap of adding features that will be useless and have a low 'value to complexity' ratio.

**Comment by schwabdidier** [comment]
Yes, I agree, that is why I want a strong idea in order to do that kind of things

**Comment by kuhlkrein** [comment]
Of course, the most important now is to focus on correcting bugs and on creating an intuitive way of customizing games. It's what people really wanted during the conference yesterday.
There are still issues with memory when playing more than 5-6 games in a row for example.
