### ISSUE TITLE
Interactive story telling

### ISSUE THREAD

**Issue by Adrieennn** [GazePlay/GazePlay#1090]
Idea for a new game
Scene accompanied by simple text or voiceover.
Player have to look at the key object (related with the text or voiceover) in the current scene to progress to the next scene. 
Involve language process, could be interesting for small children.

**Comment by Tohaker** [comment]
Sounds like the perfect kind of game to allow users to create their own stories, with simple text and image entry.

**Comment by YannRobert** [comment]
A simple book reader with text to speach is the next thing i really need, and would like to have on gazeplay

**Comment by schwabdidier** [comment]
Should be easier to do in an HTML/CSS tool (as they integrate speech synthesis).

Strongly related (maybe it is what you look for), https://albums-accessibles.org/category/par-adaptateur/adaptes-par-thierry-danigo/ Maybe we can integrate them to gazeplay (their interface is really old fashion to me and it is free but not open source)
