### ISSUE TITLE
Gradle 7 issue

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1095]
**Describe the bug**
Vincent, an internship student have an issue with gradle 7. When building the project the terminal says that gradle 6 functions are deprecated and can't be run under Gradle 7.

**To Reproduce**
Build the project with Gradle 7 I guess ?

**Expected behavior**
Maybe we could check which function is deprecated and find another way to make the project build

**Context:**
 - OS: [Windows]

**Comment by Tohaker** [comment]
Gradle 7 isn't a public release, if you're using it it's at your own risk. When it gets released, we can choose to upgrade and fix the issues, but for now it's really not a problem. 
To properly use Gradle in GazePlay, you should be running `gradlew` to install the designated version of Gradle, which is 6.0.1.
