### ISSUE TITLE
GazePlay 1.7.2

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1106]
**Is your feature request related to a problem? Please describe.**
We talked with @schwabdidier , there was a critical bug introduced in 1.7.1 in memory game (I think it's because of me and the lack of tests for this version... sry). Now that we have also fixed the problems for multiple screens and linux (tuto is still missing) we should be able to release this small update soon. What do you think @YannRobert , @Tohaker ?

**Describe the solution you'd like**
release the version 1.7.2

**Comment by Tohaker** [comment]
I'd be happy with a patch release. It's also a benefit that the installer will uninstall the old version too. Let's update the Patch Notes file anyway.

**Comment by schwabdidier** [comment]
@YannRobert your opinion ?

**Comment by YannRobert** [comment]
Do I agree that a new release is needed when there is a critical bug in latest release, and the fix is ready ?
Sure

**Comment by Tohaker** [comment]
Closing as we've now released.
