### ISSUE TITLE
Ninja sound file is empty

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1114]
**Describe the bug**
The sound file used for ninja is empty due to PR #981

**To Reproduce**
if you play ninja you should have no sound played, you can see it there:
gazeplay-games/src/main/resources/data/ninja/sounds/2009.wav

**Expected behavior**
We can either choose a new one either try to revert the old value of this file.

**Comment by Tohaker** [comment]
I'm surprised that a PR would remove the contents of a binary file, but not the file itself. If you look before that PR, does the file still have content?

**Comment by kuhlkrein** [comment]
Actually it seems that the file was not playable here already:
https://github.com/GazePlay/GazePlay/blob/17122d85e5856f4d75cbc1937bbeec2fb3ba406e/gazeplay/src/main/resources/data/ninja/sounds/2009.wav

**Comment by kuhlkrein** [comment]
So it seems that it's really to the previously quoted PR, maybe something wrong happened during the copy and it only created a new file ?

**Comment by Tohaker** [comment]
Could be the case, copying large numbers of files in one go can have issues. We should look through all the files moved and see if any others have 0 size

**Comment by Tohaker** [comment]
Ok it seems that only the ninja sound and the car images were the removed, and you fixed the car images a while back.
