### ISSUE TITLE
Ressources tests

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1115]
**Is your feature request related to a problem? Please describe.**
In order to avoid issues like #1114 

**Describe the solution you'd like**
We should list the current resources used and try to open/play them in a test class and check if there is some exception.

**Comment by kuhlkrein** [comment]
What about only checking if files exist?

**Comment by Tohaker** [comment]
That doesn't solve the problem though. In this case, the file exists but it was empty. What we need to do is have the developer run the game themselves and solve the problem when they find it. This isn't something that unit testing can solve.  PRs that introduce lots of unrelated assets should be split up into logical smaller PRs and we can then revert individual commits if we see regressions.

**Comment by Tohaker** [comment]
I'm going to close this now, if you still have concerns we can discuss it informally on Discord
