### ISSUE TITLE
Add sounds in where is the letter/number

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1116]
**Is your feature request related to a problem? Please describe.**
No question sound in where is the letter and where is the number games

**Describe the solution you'd like**
generate the sounds for both games

**Describe alternatives you've considered**
We could also generate a basic sentence for all where is it game like "where is the" and then generate the sound of the thing we are looking for. It would save some space in the resources.

**Comment by Tohaker** [comment]
We could try this: https://aws.amazon.com/polly/ - we should be able to generate all the text-to-speech we need under the free tier.

**Comment by schwabdidier** [comment]
I did that for White is the animal but it is very Time consuming

**Comment by Tohaker** [comment]
I'll have a go at the weekend - I'll write a helper script to download it all

**Comment by schwabdidier** [comment]
Possible you Think ??

**Comment by Tohaker** [comment]
https://docs.aws.amazon.com/polly/latest/dg/get-started-what-next.html

A simple python script will handle it. I can upload it to the GazePlay organisation so we can reuse it.

**Comment by kuhlkrein** [comment]
Thanks a lot @Tohaker, that would be perfect!

**Comment by Tohaker** [comment]
Repo is here: https://github.com/GazePlay/gazeplay-voice-synthesis
I've generated sounds for English, French and Chinese based on the translations already available. I will raise a PR shortly.

**Comment by schwabdidier** [comment]
Wonderful, we will reuse what you made for other languages (especially Dutch or Arbic where we have several users).

**Comment by Tohaker** [comment]
Excellent, it does take a while to generate them (it took around an hour to make 222 sounds) but you can just leave the program running and do other things

**Comment by schwabdidier** [comment]
And what about size ? Is application will become huge ?

**Comment by Tohaker** [comment]
Each sound is a couple of kB in size. I'm adding 1 or 2 MB extra to the project

**Comment by schwabdidier** [comment]
Very good :)

**Comment by Tohaker** [comment]
Closing now that it's merged
