### ISSUE TITLE
randomPositionGenerator wrong positions with double screen

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1120]
**Describe the bug**
Sometimes the call of newRandomPosition() is returning a bad value so that the target is out of the screen (seen on ninja) 

**To Reproduce**
you can try on ninja game, I tried on Linux, my second screen is on the left side of the primary one

**Expected behavior**
I don't know where the error comes from yet, but if it's not done that way we should think about returning a point with coordinates between 0 and the scene/stage max-width/height, without caring about the screen.

**Comment by schwabdidier** [comment]
Linked with new random generator ?

**Comment by kuhlkrein** [comment]
No, the new random generator has not been implemented yet I think, it's just a question of screen offsets

**Comment by schwabdidier** [comment]
Yes, it has not been implemented yet, I just wonder if we could resolve the two problems at the same time.

**Comment by kuhlkrein** [comment]
Ah no it's a different problem, it's about the computation when we have the random number, not about the random itself
