### ISSUE TITLE
Bar at the bottom of the screen

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1124]
**Describe the bug**
On some different widows OS there is a small gap between the bottom of the window and the bottom of the screen

**To Reproduce**
We noticed it on an Asus computer with windows 10

**Expected behavior**
We should remove this gap, especially in full screen where it is quite disturbing

**Comment by Tohaker** [comment]
I have also seen this issue on Windows

**Comment by schwabdidier** [comment]
It is not related to the windows bar (and gazeplay is full screen if you activated the option "hide windows bar automatically") ?
