### ISSUE TITLE
Divisor game is not using user's image library

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1125]
**Describe the bug**
it is always using the default library even if the user has added its own images

**Comment by Tohaker** [comment]
From looking at the code, this may happen if the `lapin` flag is set, does it also happen if this is not set? Additionally, is the subfolder name `divisor/basic` correct for the user folder? My guess would be that if the images aren't at this location, it will fall back to the default image directory.

**Comment by kuhlkrein** [comment]
I haven't checked yet but it's normal for the `lapin` flag (it means that we're in the `rabbit` game, sorry I think it's me who named the variable like that  ), The thing is that it should use the portrait library, so of course, if we're trying to use the divisor/basic instead, it will not works ^^ we need to change that
