### ISSUE TITLE
Easy level for where is the color game

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1127]
**Is your feature request related to a problem? Please describe.**
Some orthoptists asked for an easier level for where is the color game.

**Describe the solution you'd like**
We should create a level with only the "basic" colors (red green blue yellow + maybe white/black)

**Comment by kuhlkrein** [comment]
assigned to @PillouMatou

**Comment by Tohaker** [comment]
I can see this has been implemented now, closing.
