### ISSUE TITLE
Problem with 1.7.2 when launching on windows

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1130]
Any idea ?

![image](https://user-images.githubusercontent.com/24478346/76511605-b6ca5d00-6453-11ea-839a-99beecb4a428.png)

I then tried to install last java version:

![image](https://user-images.githubusercontent.com/24478346/76512075-67386100-6454-11ea-9ddb-5de0d01eca9a.png)

**Comment by kuhlkrein** [comment]
@Tohaker it is due to the java version I think but I don't get it, we're using openjdk 11 for compiler right ? and java 8 is last version for jre right ?

**Comment by Tohaker** [comment]
If a program is compiled in Java 11 (regardless of the vendor of that JDK) it MUST be run with that version JRE or higher. But the version we're supplying with 1.7.2 should be the Zulu JRE 11, not 8?

**Comment by Tohaker** [comment]
Can you show me the contents of the `jre/bin` file please?

**Comment by Tohaker** [comment]
I see the problem! The JRE isn't being extracted from it's enclosing folder correctly so the bat file is not finding the JRE. We need to modify the script to extract one more layer in. 
![image](https://user-images.githubusercontent.com/33665681/76514130-546f5d80-644f-11ea-92fc-52d47bc04259.png)

**Comment by Tohaker** [comment]
Got a fix incoming for this now.

**Comment by PillouMatou** [comment]
For me, the folder JRE at the version 1.7.2 on window is empty. 
I fixed the problem with copy/paste the JRE from an older version to the new version.

**Comment by Tohaker** [comment]
I downloaded the latest dev release from AWS, it had the JRE. Are you saying your local version doesn't build it with the JRE?

**Comment by kuhlkrein** [comment]
Yes, when installing it the folder inside the JRE folder is actually empty

**Comment by Tohaker** [comment]
Right... what command are you using the build the dists? You should be running `gradlew clean packageApp`

**Comment by Tohaker** [comment]
Anyway I've fixed the dists in the PR above - please try on that branch and run the command above.

**Comment by kuhlkrein** [comment]
> Right... what command are you using the build the dists? You should be running `gradlew clean packageApp`

Yes I was talking about AWS too, the build seems to work with gradlew

**Comment by Tohaker** [comment]
Which file did you download? I downloaded the windows dist from AWS and it had it in it. The contents wouldn't have changed between us downloading it.

**Comment by kuhlkrein** [comment]
Actually it's because when I executed the .exe I asked to remove the previous components, and it seems that it removed the JRE

**Comment by Tohaker** [comment]
That's odd... It should at least reinstall it. Perhaps the change in file structure confused innosetup. Leave it with me and I'll run some tests on my home PC (luckily coronavirus has made me work from home)

**Comment by Tohaker** [comment]
I tried it on my PC with the PR branch and everything installed correctly.
