### ISSUE TITLE
Update GazePlay Website without creating a release

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1172]
**Is your feature request related to a problem? Please describe.**
Because of the new project structure with master and develop branch, when we're pushing somegint on the master we're creating a release, but the gazeplay website is also on the master's branch and a modification on the website should not lead us to a new release. We should be able to push the website update without creating a release.

**Describe the solution you'd like**
can we change the website branch from master to develop for exaple ?

**Comment by kuhlkrein** [comment]
@Tohaker if you have an idea about that :)

**Comment by Tohaker** [comment]
We can run the site from a branch called gh-pages, that's just a setting change in the repo settings. I can create a new branch with the right settings to serve the site.

**Comment by kuhlkrein** [comment]
Ah ok we've seen this option in the settings with @schwabdidier but were not sure about how to use it ^^ 
we just need the branch named gh-pages and we change it in settings ?

**Comment by Tohaker** [comment]
Yep, I'll push the branch and make the change

**Comment by Tohaker** [comment]
I've made the change, however, some concessions had to be made;
We can no longer use the `docs` folder to keep the site in - when serving from `gh-pages`, it has to be in the root of the project, nothing we can do to change that. However the good news is that we won't need to change this structure in any other branch as it won't be served from there. To make a website change, all you need to do is checkout/update your `gh-pages` branch and then make a PR back into it.

**Comment by Tohaker** [comment]
A cleaner way to handle the website would be to host it in it's own repo in this organisation, but that would require changing the DNS again, if @schwabdidier is happier to do that. It would also decouple the project from the site, but it would keep the project cleaner.

**Comment by kuhlkrein** [comment]
Thank you @Tohaker for all these information ! Yes let's wait for the @schwabdidier answer. About the DNS, I think we should at least keep the current website for GazePlay Update pages (https://gazeplay.github.io/GazePlay/updates/gazeplay-1-7-2-fra/) ?

**Comment by Tohaker** [comment]
We would only need to change DNS if we move it to a new repo. Additionally, it's possible to set the A records to point directly at Github Pages and make the site more than just a redirect by adding a CNAME record. That means we can actually have www.gazeplay.net/updates/...

**Comment by Tohaker** [comment]
Closing this now that the site is served from `gh-pages`
