### ISSUE TITLE
List of useful tools for GazePlay and Tobii Eye Trackers

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1179]
- **_Tobii :_**
[ Tobii Pro Eye Tracker Manager](https://www.tobiipro.com/product-listing/eye-tracker-manager/)
[ Stream Engine 3.3.0 for Linux x64](https://developer.tobii.com/download-packages/stream-engine-3-3-0-for-linux-x64/)
[ Stream Engine 3.3.0 for macOS x86](https://developer.tobii.com/download-packages/stream-engine-3-3-0-for-macos-x86/)
[ Stream Engine 3.3.0 for Windows x64](https://developer.tobii.com/download-packages/stream-engine-3-3-0-for-windows-x64/)
[ Eitol tobii_eye_tracker_linux_installer github repo](https://github.com/Eitol/tobii_eye_tracker_linux_installer)

**Comment by Tohaker** [comment]
This would be more suitable to be in our Wiki, I will add it.
