### ISSUE TITLE
idea from community (Jessica Martinez) : define a time length or a number of actions for each game

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#1194]
**Is your feature request related to a problem? Please describe.**
Many games never stop (for instance, cream pie), the idea is to stop them after a while

**Describe the solution you'd like**
In the options, the possibility to define a time length or a number of actions for each game

**Describe alternatives you've considered**
It could stay like it is now

**Additional context**
no

**Comment by schwabdidier** [comment]
@PillouMatou : This one

**Comment by kuhlkrein** [comment]
fixed by #1203
