### ISSUE TITLE
Idea from community (Jessica Martinez) : new game, bottle 

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#1195]
**Is your feature request related to a problem? Please describe.**
a new game which would constit in send balls to break bottles

**Describe the solution you'd like**
on the screen you have n bottle and when you fix somewhere, you send a ball. when a ball hit a bottle, it break it. 

**Describe alternatives you've considered**
no alternative 

**Additional context**
no

**Comment by kuhlkrein** [comment]
("jeu de massacre", or "chamboule tout" in french, could be also helpful in order to find some design ideas)

**Comment by schwabdidier** [comment]
Yes for this games, design is definitely important.

**Comment by schwabdidier** [comment]
resolved, game now exists
