### ISSUE TITLE
Biboule jump has parallel lines in heatmap when using an eye tracker or mouse control

### ISSUE THREAD

**Issue by Adrieennn** [GazePlay/GazePlay#1225]
![image](https://user-images.githubusercontent.com/47210173/91449249-2c4bad80-e87b-11ea-9501-e77e88079043.png)

the coordinates go to the upper left corner all the time for no reason

a list of games that has this behaviour:

-Robot, Biboule(the shooter games?)
-Biboule jump
-Scratch card, Block
-Rock paper scissor
-Bottle

**Comment by Adrieennn** [comment]
Robot, blocks, bottle scratch cards have the same issue

**Comment by kuhlkrein** [comment]
fixed by #1223
