### ISSUE TITLE
Modify stats fixation and heatmap picture

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1227]
**Describe the solution you'd like**
Instead of displaying a picture, we would like to display the trajectory of the fixation sequence on top of the current screenshot+heatmap image, so that we could switch between the display of the gaze, the mouse or both

**Describe alternatives you've considered**
We could also create 3 different images instead

**Comment by schwabdidier** [comment]
And then, we can also add length between two fixations on the edge

**Comment by kuhlkrein** [comment]
for now #1223 is implementing multiple picture option
