### ISSUE TITLE
mouse recording should be stopped when BBB is pressed

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#1241]
**Describe the bug**
mouse recording continues when BBB is pressed then it records sound modification or other interaction with this menu 

**Expected behavior**
mouse recording should be temporally stopped as long as menu is open (maybe the game should also be stopped 

**Screenshots**

**Context:**
 - OS: [Windows 10, Linux, Mac, ...] all
 - Java Version: n/a
 - GazePlay Version: development one

**Additional context**

**Comment by schwabdidier** [comment]
Should be resolved

**Comment by Noars** [comment]
I send a Pull Request for this issue ! (PR #1321)

**Comment by schwabdidier** [comment]
Not resolved
