### ISSUE TITLE
heapMap issue (for bottle game for example)

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1247]
**Describe the bug**
when playing some games when the convex hull is enabled the full heapmap exception is triggered

**To Reproduce**
play 3/4 successive bottle game to trigger the error.

**Comment by kuhlkrein** [comment]
@schwabdidier does this feature is really usefull ?

**Comment by kuhlkrein** [comment]
_Note: For now this feature has been disabled in gazeplay to avoid this exception_

**Comment by schwabdidier** [comment]
still relevant ?

**Comment by kuhlkrein** [comment]
If we want to use convex hull later yes I guess
