### ISSUE TITLE
Menu is shown after waiting

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#1251]
**Describe the bug**

**To Reproduce**
1. Click on a game
2. Wait, the menu is shown during one second before game is actually launch
**Expected behavior**
The menu should not be shown

** screenshot

![Uploading 97111103...]

**Context:**
 - OS: windows 10
 - GazePlay Version: development version

**Comment by kuhlkrein** [comment]
Yes actually for now we're displaying the laoding screen 5 seconds before going back to normal menu to give time to the game window to launch. It should be fine on most of the 4Go-8Go Ram PC but maybe some need more ?
