### ISSUE TITLE
Some elements disappear in the menu

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#1252]
**Describe the bug**

**To Reproduce**
Happen at least three times, maybe related to where is it but not sure. 

**Expected behavior**

**Screenshots**
![Uploading 97111023...]

**Context:**
 - OS: Windows 10
 - GazePlay Version: development version

**Comment by kuhlkrein** [comment]
In the home screen game menu ? or in the menu bar ?
