### ISSUE TITLE
Configurable Where is it BOM, MP3 and other error

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1272]
**Describe the bug**
In order to avoid errors due to UTF8 BOM in some csv files or in the name of some files like we had recently with the neuroscience master students we should create a folder management system in configuration as it is done for custom magiccards, blocs etc...

**Context:**
GazePlay-Eval

**Comment by schwabdidier** [comment]
@kuhlkrein to close or not to close ?
