### ISSUE TITLE
Webpage : counter has been modified

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#1273]
New counter is https://somsubhra.com/github-release-stats/?username=GazePlay&repository=GazePlay&page=1&per_page=50

**Comment by Tohaker** [comment]
Is this a bug? What's the problem here?

**Comment by schwabdidier** [comment]
Now, the page only shows last 5 releases instead of all releases.

**Comment by Tohaker** [comment]
Are you sure? I can see all releases on that link

**Comment by schwabdidier** [comment]
Yes but the one on the website is not good

**Comment by Tohaker** [comment]
Well there's an option to change the number shown on that page, is it really a problem? Anyone that wants to see the total downloads can still find them

**Comment by schwabdidier** [comment]
I think that people simply misunderstand and consider that the number shown is the actuel number of downloads.

**Comment by schwabdidier** [comment]
This counter doesn't work at all anymore. We have to add another one. 

For instance : [https://hanadigital.github.io/grev/?user=GazePlay&repo=GazePlay](https://hanadigital.github.io/grev/?user=GazePlay&repo=GazePlay)

**Comment by Tohaker** [comment]
I'll raise a PR now - here's what it will look like: https://tohaker.github.io/GazePlay/help/fr
