### ISSUE TITLE
Orthographe en Langue = Français

### ISSUE THREAD

**Issue by Noars** [GazePlay/GazePlay#1285]
Dans les paramètres -> Paramètres des Zones d’Intérêt mettre les accents sur le mot Intérêt qui est actuellement écris "Interet".

**Comment by Noars** [comment]
I send a Pull Request for this issue !

**Comment by schwabdidier** [comment]
Please indicate the PR number (good practice)

**Comment by Noars** [comment]
PR #1309

**Comment by schwabdidier** [comment]
still relevant @Noars ?
