### ISSUE TITLE
Changing the variant of a game

### ISSUE THREAD

**Issue by Noars** [GazePlay/GazePlay#1288]
Being able to change the variant of a game without leaving the game and re-entering it.

**Comment by schwabdidier** [comment]
What are possibilities do that ? It doesn't seem obvious

**Comment by Philippe-meylan** [comment]
In terms of UI, rather than going back to the home page, you skip directly to the options of the game.

**Comment by schwabdidier** [comment]
to do ?

**Comment by schwabdidier** [comment]
to do ?
