### ISSUE TITLE
Game Settings

### ISSUE THREAD

**Issue by Noars** [GazePlay/GazePlay#1291]
When you choose a parameter, it applies to all games.
It should be possible to modify them and keep them for each game.
Valid for all game parameters except the exit key.

**Comment by schwabdidier** [comment]
Is it for all options or some particular option. To me, fixations may be different for each games. in the same way than sound and speed ?

**Comment by Noars** [comment]
I send a Pull Request for this issue (PR #1319)

**Comment by schwabdidier** [comment]
Can we close it ?
