### ISSUE TITLE
Piano Game

### ISSUE THREAD

**Issue by Noars** [GazePlay/GazePlay#1294]
Combine visual cueing with the pitch of the sound which would require to position the keyboard horizontally (like a piano) and it is the pointing which would give the sound.
Thus small melodies could be invented.

**Comment by schwabdidier** [comment]
I don't understand (I think it is because I am not a musician)

**Comment by Philippe-meylan** [comment]
What we said is that for a given sound there should be a unique key on the keyboard.
A piano keyboard is far more convenient and realistic than a circular object.
For a note ("Do" / "C" for example ) we may have several keys corresponding to the different octaves
but each specific sound corresponds to a single key and conversely.
The game can be played in two ways :
- the machine successively displays the keys of a melody while the user selects the keys which are then played
- the user invents a melody by selecting successive keys that the machine plays

**Comment by schwabdidier** [comment]
@kuhlkrein you are the author of this game, can you think about that ?
