### ISSUE TITLE
Piano Game Bug

### ISSUE THREAD

**Issue by Noars** [GazePlay/GazePlay#1295]
There are always 2 keys on the left that never light up.

**Comment by schwabdidier** [comment]
Still unresolved ?

**Comment by Iluvrog** [comment]
[https://github.com/GazePlay/GazePlay/pull/1355](url)
I think it work

**Comment by Iluvrog** [comment]
#1355 
I think it work

**Comment by kuhlkrein** [comment]
@schwabdidier @Iluvrog actually it is needed, the keys are "do re mi fa sol la si do" and they are played only if they appear in the sound, like in a normal piano
