### ISSUE TITLE
Space Game

### ISSUE THREAD

**Issue by Noars** [GazePlay/GazePlay#1300]
To make the shooting more controllable, at the moment it's more a matter of chance.

**Comment by schwabdidier** [comment]
Uneasy. How to manage spaceship displacements and shooting only with gaze ?

**Comment by Philippe-meylan** [comment]
I think the trouble comes from the fact that there is a big latency between the time you shoot and the time the bullet reaches the top of the screen. You don't really control the shoot to the target;
A solution could be :
- only shoot if the gun is motionless
- launch fast bullets which can quickly reach the targets (possibly adapt the size of the target)
