### ISSUE TITLE
Coloring Game Terms

### ISSUE THREAD

**Issue by Noars** [GazePlay/GazePlay#1302]
Change the terms : 
- "Load" by "Open";
- "Save" to "Save"; (en français : "sauvegarder" par "enregistrer")

**Comment by schwabdidier** [comment]
these are two different issues. Keep the actual language when needed (especially for translation)

**Comment by Noars** [comment]
Issue modified !

**Comment by schwabdidier** [comment]
done or not @Noars  ?
