### ISSUE TITLE
Action-Reaction Games should be using dwell-time fixation with zero duration

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1318]
**Is your feature request related to a problem? Please describe.**
If we were adding the dwell-time fixation implementation for all games it will create a more homogenous code and will make us able to test those games with dwell-fixation different than zero, what could be interesting, for example with bloc game.

**Describe the solution you'd like**
Adding a progressIndicator to all objects that were currently being trigered by an "ENTER" event only, or replace them with a progress button

**Comment by schwabdidier** [comment]
Can we close it ?
