### ISSUE TITLE
Create individual game shortcut

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1320]
**Is your feature request related to a problem? Please describe.**
Request from a user: "si les jeux pouvaient être proposés individuellement ce serait vraiment plus simple pour les intégrer dans les Mind express ou GRID"

**Describe the solution you'd like**
We should find a way to give shortcuts for different games for the user, for example a shortcut for ninjan will display the variant possibility and then launch the selected one, another example, for sounds of life farm, it will imediatly launch the farm game etc...

**Describe alternatives you've considered**
We can ask the user if they want to create a shortcut, of make the shortcut available for download on the website

**Comment by schwabdidier** [comment]
@kuhlkrein  done or not ?
