### ISSUE TITLE
Increase elements size

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1335]
**Is your feature request related to a problem? Please describe.**
For games like ninja, creampie, we should let the user choose if (s)he wants a bigger or smaller size for the elements displayed on screen.

**Describe the solution you'd like**
Size could be adjustable thanks to a slider in the options panel

**Comment by Noars** [comment]
Maybe, put in the settings a line with the value of the size of the element that you want and a reset button next to it ?
