### ISSUE TITLE
Ninja game: unexpected translation in random mode

### ISSUE THREAD

**Issue by verafili** [GazePlay/GazePlay#1337]
**Describe the bug**
When a new target appears on the screen, it follows a trajectory from the start point P1 to the next point P2. Then the target is supposed to move from P2 to the next point P3. However, the object change somehow its last position (from P2 to some new random point) without any translation, and then all next translations are executed properly.

This bug occurs for each new target in a game.

**Expected behavior**
The target should move _continuously_ from point to point without any unexpected movements.

**Comment by PillouMatou** [comment]
i will work on it

**Comment by kuhlkrein** [comment]
fixed by #1352
