### ISSUE TITLE
Mouse event triggered at game launch

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1339]
**Is your feature request related to a problem? Please describe.**
It looks like there is a mouse position problem when launching some games.
For example, if after launching a game "where is this" (2x2) the mouse is not put on the border of the screen, when the proposals are displayed, there is directly 1 box that is selected. The one hovered by the mouse cursor.

**Describe the solution you'd like**
maybe we should wait for a small amount of time after launching any of the game to avoid this issue. 
(I think there is already an option for where is it - like games actually)

**Comment by Iluvrog** [comment]
[https://github.com/GazePlay/GazePlay/pull/1354](url)
This solution is not perfect but it work

**Comment by Iluvrog** [comment]
#1354 
This solution is not perfect but it work
