### ISSUE TITLE
Update tobii_eyex_4c interaction option name to tobii

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1342]
**Is your feature request related to a problem? Please describe.**
Other tobii devices than eyex and 4c are compatible with gazeplay, so we should generalize the option ton "tobii"

**Describe the solution you'd like**
We can either change only the name displayed in the setting pannel or rename the whole configuration value

**Comment by Iluvrog** [comment]
[https://github.com/GazePlay/GazePlay/pull/1356](url)

**Comment by Iluvrog** [comment]
#1356
