### ISSUE TITLE
Not a json format error when displaying stats for some games, leading user to be unable to exit game.

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1343]
**Describe the bug**
Sometimes for some user using the GazePlay Eval version , there is an error about the JSON of saved stats that lead the user to be unable to exit the game by clicking the green house.

**Context:**
Windows 10 with GazePlay eval on a normal user session with a pc with huge Administrator restrictions (maybe it's due to some restrictions)

**Comment by schwabdidier** [comment]
still relevant ?
