### ISSUE TITLE
Same images one after the other in opinion

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1390]
**Is your feature request related to a problem? Please describe.**
We should avoid having the two same images one after the other in the opinion game. It makes the user think that its action had no impact or that the game is buggy.

**Describe the solution you'd like**
We should take a random image, excluding the old image we had

**Describe alternatives you've considered**
We should check if the new image is the same as the old one and take another image in this case

**Comment by Iluvrog** [comment]
#1392
