### ISSUE TITLE
Untranslated scenes in profils other than default profile

### ISSUE THREAD

**Issue by verafili** [GazePlay/GazePlay#1398]
**Describe the bug**
When GazePlay is launched as a particular user profile, some scenes such as statistics at the end of the game or the Home barre during the game are not translated.

In fact, the problem is that those scenes are somehow translated to the language selected in the Default profile. For instance, if the language of the default profile is English, then the statistics will be in English no matter the language selected by the user in a given profile.

**Expected behavior**
All menus/scenes are written in the same language which was selected by a particular user.

**Comment by kuhlkrein** [comment]
how to fix:

add `translator.notifyLanguageChanged();` before `leftControlPane = new GridPane();` in `public void createControlPanel(@NonNull GazePlay gazePlay, @NonNull Stats stats, GameLifeCycle currentGame)`

**Comment by kuhlkrein** [comment]
fixed
