### ISSUE TITLE
select user in french

### ISSUE THREAD

**Issue by Iluvrog** [GazePlay/GazePlay#1465]
When Gazeplay isn't in french, the "new user" and "default user" are still in french
![erreur_titre](https://user-images.githubusercontent.com/81555413/131351152-be629294-f967-4185-8dd6-224c00d6e911.png)

**Comment by kuhlkrein** [comment]
Are you sure that you changed the language of the default user ? the account page has the language of the default account

**Comment by Iluvrog** [comment]
> Are you sure that you changed the language of the default user ? the account page has the language of the default account

Ah ok, I thinked it was the same language for all users
