### ISSUE TITLE
strange behavior in piano game

### ISSUE THREAD

**Issue by Iluvrog** [GazePlay/GazePlay#1487]
when you play with the fixation>0, all the keys have a delay expect the central key

**Comment by verafili** [comment]
i'll take this. There is also a problem with the progress bar on the right button key.
![image](https://user-images.githubusercontent.com/62764646/132343026-a917960e-e78c-4bfa-b50d-ae8043c49089.png)

**Comment by verafili** [comment]
I'll take this. There is also a problem with the progress bar on the bottom right key.
![241512774_372262377703330_7199233231162579990_n](https://user-images.githubusercontent.com/62764646/132343374-1f9affbb-06d4-4a52-99df-88ae3d1654a3.png)

**Comment by verafili** [comment]
#1510
