### ISSUE TITLE
where is it with tobii selected but played with the mouse

### ISSUE THREAD

**Issue by Iluvrog** [GazePlay/GazePlay#1489]
When you play a where is it game with tobii selected but played with mouse, the game select automaticaly the central card

**Comment by Iluvrog** [comment]
same bug with the order game

**Comment by Iluvrog** [comment]
same with biboule game

**Comment by Iluvrog** [comment]
same #1491

**Comment by Iluvrog** [comment]
same in blocks and scratchcards

**Comment by Iluvrog** [comment]
same in divisor

**Comment by Iluvrog** [comment]
same in the operations game

**Comment by Iluvrog** [comment]
same in rush hour, coloring, bottle, farm and egg game

**Comment by Iluvrog** [comment]
same with the dice in horses game

**Comment by Iluvrog** [comment]
same in sliding puzzle

**Comment by kuhlkrein** [comment]
Liked to #1396
