### ISSUE TITLE
bug in the user menu 2

### ISSUE THREAD

**Issue by Iluvrog** [GazePlay/GazePlay#1499]
The scroll bar doesn't appear in the launch but only after select a user
![barre1](https://user-images.githubusercontent.com/81555413/132027711-9923c9e0-2a11-40a2-9a0f-a082d782d369.png)
![barre2](https://user-images.githubusercontent.com/81555413/132027725-063fc017-2b87-4a95-8fc6-ebf4b9429177.png)

**Comment by kuhlkrein** [comment]
Should not be a problem anymore when we will reduce the size of the user name
