### ISSUE TITLE
Difficultés à personnaliser le jeu ‘Où est-ce’

### ISSUE THREAD

**Issue by titacava** [GazePlay/GazePlay#1549]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/cavadint/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/cavadint/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/cavadint/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/cavadint/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=FR-CH style='tab-interval:35.4pt'>

<p class=MsoNormal>Bonjour,<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoPlainText>Je me permets de vous contacter au sujet du logiciel
GazePlay avec lequel je rencontre quelques difficultés pour configurer le
répertoire personnalisé du jeu ‘Où est-ce’.<br style='mso-special-character:
line-break'>
<![if !supportLineBreakNewLine]><br style='mso-special-character:line-break'>
<![endif]><o:p></o:p></p>

<p class=MsoPlainText>Je souhaite tout d'abord vous remercier de proposer un
logiciel aussi complet et de si grande qualité en accès libre.<br
style='mso-special-character:line-break'>
<![if !supportLineBreakNewLine]><br style='mso-special-character:line-break'>
<![endif]><o:p></o:p></p>

<p class=MsoPlainText>Doctorante à l'Université de Genève, j'étudie les apports
potentiels de l'oculométrie pour évaluer et entraîner des compétences socio
émotionnelles insoupçonnées chez des jeunes en situations de polyhandicap.
Après une première phase d'évaluation, je m'apprête à débuter une phase
d'entraînement pour laquelle je prévois d'utiliser certains jeux de GazePlay
dont notamment ‘Où est-ce’. Malheureusement, je peine à le personnaliser malgré
les explications données à la rubrique FAQ de votre site.<o:p></o:p></p>

<p class=MsoPlainText>La première difficulté que je rencontre est que le
dossier ‘where-is-it’ n'apparaît pas dans le dossier GazePlay
(C:\Users\&lt;username&gt;\GazePlay).<o:p></o:p></p>

<p class=MsoPlainText>J'ai donc tenté d'en créer un moi-même et d'y intégrer
les différents éléments que vous mentionnez mais j'ai dû faire une erreur
quelque part car en lançant le jeu les images correctes/incorrectes ne
correspondent pas aux bons fichiers.<o:p></o:p></p>

<p class=MsoPlainText><o:p>&nbsp;</o:p></p>

<p class=MsoPlainText>Je souhaiterais entraîner la discrimination des émotions
en demandant au joueur &quot;où est le visage joyeux/triste/en colère&quot;
parmi différents visages émotionnels.<o:p></o:p></p>

<p class=MsoPlainText>Pour ce faire voici les éléments que j'ai ajouté dans le
dossier ‘where-is-it’ créé:<o:p></o:p></p>

<ul style='margin-top:0cm' type=disc>
 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo1'>un
     dossier ‘image’, composé de 3 sous-dossiers (‘colere’ ‘joie’ ‘tristesse’)
     regroupant chacun les 4 mêmes fichiers (colere.png, joie.png, neutre.png,
     tristesse.png)<o:p></o:p></li>
 <li class=MsoPlainText style='mso-list:l0 level1 lfo1'>un dossier ‘pictos’
     contenant les 3 fichiers correspondant à la réponse correcte de chaque
     question (colere.png, joie.png, tristesse.png)<o:p></o:p></li>
 <li class=MsoPlainText style='mso-list:l0 level1 lfo1'>un dossier ‘sounds’
     (vide)<o:p></o:p></li>
</ul>

<p class=MsoPlainText><o:p>&nbsp;</o:p></p>

<p class=MsoPlainText>J'espère avoir été suffisamment précise pour que vous
puissiez m'indiquer les modifications à effectuer pour que mon jeu personnalisé
fonctionne comme espéré. <o:p></o:p></p>

<p class=MsoPlainText><o:p>&nbsp;</o:p></p>

<p class=MsoPlainText>Je vous remercie par avance pour votre temps et vous
adresse mes meilleures salutations. <o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

  | Thalia   Cavadini    Doctorante, boursière FNS
-- | --

<p class=MsoNormal style='margin-bottom:2.5pt'><b><span style='font-size:9.0pt;
font-family:"Arial",sans-serif;color:gray;mso-fareast-language:EN-US;
mso-no-proof:yes'>Faculté de psychologie et des sciences de l’éducation (FPSE)<o:p></o:p></span></b></p>

<p class=MsoNormal style='margin-bottom:2.5pt'><b style='mso-bidi-font-weight:
normal'><span style='font-size:9.0pt;font-family:"Arial",sans-serif;color:gray;
mso-fareast-language:EN-US;mso-no-proof:yes'>Laboratoire du développement
sensori-moteur, affectif et social (SMAS)<span style='mso-bidi-font-weight:
bold'><o:p></o:p></span></span></b></p>

<p class=MsoNormal style='margin-bottom:2.5pt'><b style='mso-bidi-font-weight:
normal'><span style='font-size:9.0pt;font-family:"Arial",sans-serif;color:gray;
mso-fareast-language:EN-US;mso-no-proof:yes'>Université de Genève</span></b><span
style='font-size:9.0pt;font-family:"Arial",sans-serif;color:gray;mso-fareast-language:
EN-US;mso-no-proof:yes'> | Uni Mail, 40 bd du Pont-d’Arve, 1211 Genève 4,
Suisse<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:9.0pt;font-family:"Arial",sans-serif;
color:gray;mso-fareast-language:EN-US;mso-no-proof:yes'><a
href="mailto:Thalia.Cavadini@unige.ch"><span style='color:gray;mso-fareast-language:
JA;text-decoration:none;text-underline:none'>Thalia.Cavadini@unige.ch</span></a>
| Bureau M3127 | Tél.&nbsp;+41(0)22&nbsp;379&nbsp;90&nbsp;50 <o:p></o:p></span></p>

<p class=MsoNormal><b><u><span style='font-size:9.0pt;font-family:"Arial",sans-serif;
color:#CF0063;mso-no-proof:yes'><a
href="http://www.unige.ch/fapse/sensori-moteur/"><span style='color:#CF0063'>www.unige.ch/fapse/sensori-moteur/</span></a></span></u></b><b><span
style='font-size:9.0pt;font-family:"Arial",sans-serif;color:#CF0063;mso-no-proof:
yes'> </span></b><span style='font-size:9.0pt;font-family:"Arial",sans-serif;
color:gray;mso-fareast-language:EN-US;mso-no-proof:yes'>| </span><b><u><span
style='font-size:9.0pt;font-family:"Arial",sans-serif;color:#CF0063;mso-no-proof:
yes'><a href="https://www.unige.ch/fapse/babylab/"><span style='color:#CF0063'>https://www.unige.ch/fapse/babylab/</span></a></span></u></b><b><span
style='font-size:9.0pt;font-family:"Arial",sans-serif;color:#7F7F7F;mso-fareast-language:
FR;mso-no-proof:yes'><o:p></o:p></span></b></p>

</body>

</html
[questions.csv](https://github.com/GazePlay/GazePlay/files/7338602/questions.csv)
>

**Comment by TheEaterr** [comment]
Bonjour,
Chaque fichier ne doit contenir que les images correspondant à la catégorie du fichier (ie le fichier colère peut contenir plusieurs images mais elles doivent toute représenter la colère). Le programme utilise les images dans les autres dossiers pour génerer les questions.
Pour faire court, enlevez les 3 images ne correspondant pas au titre du fichier pour chacun des dossiers et cela devrait fonctionner.
