### ISSUE TITLE
adds in contribribution.md

### ISSUE THREAD

**Issue by PillouMatou** [GazePlay/GazePlay#1557]
add reformat code in contribution.md

**Comment by schwabdidier** [comment]
what is it ?

**Comment by PillouMatou** [comment]
when we push the code, we reformat it with 2 options accessible with the shortcut :  ctrl + alt + L

![image](https://user-images.githubusercontent.com/43779207/172137929-355b1ae9-9797-434a-8369-4a9888bbdae1.png)
