### ISSUE TITLE
find a way to access to the music default files in a "cleaner" way 

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#497]
musicFolder = (new File(".")).getAbsolutePath()+"/gazeplay-data/src/main/resources/data" + File.separator + "home" + File.separator + "sounds";

I'm currently using this path to access the basic default song folder, but I'm pretty sure that a function can give it to me directly.
I searched in the Utils classes, but it returned me only the paths of the directory generated in the Home of the user, to save heatmaps, configs etc...

the function is 
private static void changeMusicFolder(final String newMusicFolder)
in the ConfigurationContext class

**Comment by schwabdidier** [comment]
is it still an open issue @kuhlkrein ?

**Comment by kuhlkrein** [comment]
Yes, in my opinion, we should have a look at the _playSound_ function of the _Utils.java_ class and try to do something similar. If I remember well here, the problem was mainly a problem of path for the sounds files. But I didn't have any problem when creating the egg game yesterday, so we can maybe solve it easily.

**Comment by Tohaker** [comment]
I'm pretty sure this issue has been fixed since #891
