### ISSUE TITLE
Tutorial with visual support on the website

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#543]
Explaining for example how to create folder containing portrait images etc

**Comment by kuhlkrein** [comment]
We noticed that in the center we went last time, the person in charge of children was not really used to use this functions because it was maybe too complex for her

**Comment by schwabdidier** [comment]
It is true, what do you suggest to do ?

**Comment by kuhlkrein** [comment]
Maybe we could try to do a guided tutorial, showing the locations, windows and different possibilities for creating folders (portraits, memories ...)

**Comment by schwabdidier** [comment]
You mean right clic new folder ?

**Comment by kuhlkrein** [comment]
![image](https://user-images.githubusercontent.com/24478346/42371751-ad4a825a-8110-11e8-8cec-96a358ffa44c.png)

![image](https://user-images.githubusercontent.com/24478346/42371786-c1ba4f68-8110-11e8-83d6-c65a55bae351.png)

![image](https://user-images.githubusercontent.com/24478346/42371810-d40370b4-8110-11e8-8956-1ac2e7ba6dc4.png)

![image](https://user-images.githubusercontent.com/24478346/42371848-efa0419e-8110-11e8-8c44-8be3750468e8.png)

![image](https://user-images.githubusercontent.com/24478346/42371869-fed0deda-8110-11e8-83da-9bb0d7bd1c6d.png)

![image](https://user-images.githubusercontent.com/24478346/42371884-0896aa6c-8111-11e8-9cfd-0c25a33860d6.png)

![image](https://user-images.githubusercontent.com/24478346/42371899-143523c6-8111-11e8-9438-050bf7b2739b.png)

Something like this for example, really more guided, with smaller pictures

**Comment by schwabdidier** [comment]
as you did it, we can use it but it could be done for so many os and os version...

**Comment by Tohaker** [comment]
This was on the old site, it can be ported over to the new one

**Comment by schwabdidier** [comment]
the address of the old site gazeplay.wordpress.fr
