### ISSUE TITLE
Some seconds without interaction at the beginning of games

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#596]
for instance for "where is it" games. During this period, children can have a look everywhere on the screen without interaction (idea from Leen)

**Comment by kuhlkrein** [comment]
I guess we could add a timeline just after the translation of the question and then we can add the gaze/mouse event of the pictures after this timeline (instead of adding it after the picture creation)

**Comment by schwabdidier** [comment]
thank you for the idea. Sounds very easy. I will try.
