### ISSUE TITLE
Bundle including java

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#602]
In order to have everything in a single bundle.

https://stackoverflow.com/questions/39193868/bundle-java-program-for-mac-users-with-maven-from-gnu-linux

Should be possible to do the same for windows and linux.

**Comment by Tohaker** [comment]
Here is an interesting article around this: https://medium.com/@adam_carroll/java-packager-with-jdk11-31b3d620f4a8
Seems a bit difficult to automate, but its a start, and works with OpenJDK 11.

**Comment by Tohaker** [comment]
Has #984 solved this issue?
