### ISSUE TITLE
Quits keys : keyboard is considered as qwerty on MacOs

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#664]
@petinhoss7 : on my azerty keyboard, I have to make a to exit (instead of q).

**Comment by petinhoss7** [comment]
@schwabdidier You mean you have to make a to exit instead of q ?

**Comment by schwabdidier** [comment]
Right, I modify my comment

**Comment by petinhoss7** [comment]
@schwabdidier : A simple fix, for now, would be to change the available keys in the settings to the letters that are the same on both keyboards. However, I will search on the web to know why this is happening.

**Comment by Tohaker** [comment]
Is this still a problem? I made something that changes the key based on locale but I think I didn't understand the question, did you want the Q key to quit regardless of Keyboard layout?
