### ISSUE TITLE
MacOs bug : Problem of transparency in some images

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#668]
@sannaraek
<img width="1280" alt="Capture d’écran 2019-03-18 à 20 24 08" src="https://user-images.githubusercontent.com/23239584/54558038-fd11eb00-49bc-11e9-864b-411887d7bde4.png">

**Comment by Sannaraek** [comment]
<img width="1680" alt="Screenshot 2019-03-18 at 10 19 25 PM" src="https://user-images.githubusercontent.com/19200270/54564386-f2ab1d80-49cb-11e9-92d7-086d8438fd4d.png">

This is strange, the frogs do not have a white a background and are moving on my machine

**Comment by schwabdidier** [comment]
Yes ! Please other students try to check if you experiment the same bug.

**Comment by teoblachere** [comment]
It works fine on mine too
![Screenshot from 2019-03-21 17-02-44](https://user-images.githubusercontent.com/19331032/54766239-3df74300-4bfb-11e9-9786-10a5f616b1aa.png)
Running on linux.

**Comment by Sannaraek** [comment]
@schwabdidier The game appears to be running normally on Linux and MAC although I don't have a window's machine to confirm it. Were you by any chance on a window machine when you encountered the bug?

**Comment by schwabdidier** [comment]
No. It is on my Mac !!

**Comment by schwabdidier** [comment]
The bug is also with explosions in magic potions
