### ISSUE TITLE
[WebSite] Games have to be updated 

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#761]
Games have to be updated on the WebSite
https://gazeplayeng.wordpress.com/games/
https://gazeplayfra.wordpress.com/jeux/

In order to do that it should be in the [game-fra](https://github.com/schwabdidier/GazePlay/blob/master/Games-fra.md) and [game-eng](https://github.com/schwabdidier/GazePlay/blob/master/Games-eng.md) file (with thumbnails)

**Comment by Tohaker** [comment]
Now that we're on the new site, these games are all updated
