### ISSUE TITLE
One version per os ?

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#887]
Now, thanks to @Tohaker we have a version which seems to works on Windows (I say seems because, it works on my two windows computer but often we find bugs when people use it on their own computer). 

I wonder if we should have a release per os (at least one for Windows, one for Linux, one for macOS) and one without JVM (for advanced users).

**Comment by Tohaker** [comment]
The jlink plugin in Gradle does allow for multiple release versions, where we can specify JVM args for various OSs. It has a package task for creating .exe, .dmg and .deb files to actually perform an install on a users computer. I've not used this before, but would be happy to investigate the integration into the release process.

See here: https://badass-runtime-plugin.beryx.org/releases/latest/#_the_jpackage_script_block

**Comment by schwabdidier** [comment]
Oh yes, if you can do it, it would be great for GazePlay ! For now, GazePlay appears "amateur" for some people because of that kind of things.
