### ISSUE TITLE
Sound problem (same one or new ? )

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#893]
I received this message : 

I have sound problems. For example the game with no sound letters.
Sometimes we can't throw them and get out.
Other games depending on the moment may or may not play the sound.

@Tohaker : I guess it is the bug #890 and you resolved it, isn't it ?

**Comment by schwabdidier** [comment]
@Tohaker may you check ?

**Comment by Tohaker** [comment]
I believe this is fixed now.

**Comment by Tohaker** [comment]
@schwabdidier This should be resolved, can you check?

**Comment by schwabdidier** [comment]
No, it was a problem form an end user. I close it, we will see
