### ISSUE TITLE
A new JVM for each game

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#894]
Issue based on a discussion with @YannRobert.

Each time a game is launched, it should be launch through a new JVM. This feature would have two advantages :
1) We have random issues with some games. Sometimes, they don't seem to be completly closed and we don't know why... With a complete separately JVM, we won't have this problem anymore.
2) To work on a game, it will be easier as they can be launch independently

**Comment by Tohaker** [comment]
I can see the benefit of this, it will definitely be worthwhile to modularise the project even more. For example:
* 'Launcher' module
* Game 1 module
* Game 2 module
...

This would also benefit testing as things are more encapsulated.

**Comment by kuhlkrein** [comment]
Hello @Tohaker and @schwabdidier , to do so you mean that each "game module" should be a different application? And we launch them by using Application.launch() ?

**Comment by schwabdidier** [comment]
yes certainly, what is you opinion @Tohaker ?

**Comment by Tohaker** [comment]
It would greatly simplify testing, however I'm not sure if this would work with the Spring Framework in place. That said, I've not worked much with either way to making projects before so I'd have to try it out first.

**Comment by schwabdidier** [comment]
@YannRobert you introduced spring to the project, any idea on @Tohaker's concern ?
