### ISSUE TITLE
Fix packaging

### ISSUE THREAD

**Issue by YannRobert** [GazePlay/GazePlay#918]
Since project moved to gradle, 
the dist file is not built as expected, and is unusable.

**Comment by Tohaker** [comment]
Can you elaborate? It builds fine for me and the dist package is included as both a folder and a set of resources.

**Comment by YannRobert** [comment]
Please try to execute GazePlay from the provided .bat file.

It fails on the Java command line.

**Comment by Tohaker** [comment]
This appears to have been caused by the introduction of SpringBoot dependencies into gradle, not Gradle itself. Instead of creating one dist file with lib, data and scripts, the script is put into another .zip called `gazeplay-project-boot` along with a shadowJar.

**Comment by YannRobert** [comment]
Found multiple issues

- jar references in .sh or .bat files is gazeplay-project-1.6.2-SNAPSHOT.jar instead of gazeplay-1.6.2-SNAPSHOT.jar
- when unzipping the distribution zip file, unzip will prompt for a confirmation to overwrite some files (all files in the bin directory) acting like if the zip contains multiple entries for the same files
- the gazeplay-1.6.2-SNAPSHOT.jar file contains an empty manifest so that it is not an executable JAR file, as assumed by the .sh/.bat files

**Comment by Tohaker** [comment]
Sounds like a configuration issue in the Gradle files. I'm not sure if I'll get a chance to look at it soon, but if you want to try to fix it I'll be happy to help you out!

**Comment by YannRobert** [comment]
Yes I am trying to fix as much as possible.

**Comment by Tohaker** [comment]
Did the JAR execute after this PR?

**Comment by Tohaker** [comment]
I believe this Issue is ready be closed @schwabdidier
