### ISSUE TITLE
Videos of games

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#920]
Simple screenshot for a game

**Comment by kuhlkrein** [comment]
I just used 

      `  System.setProperty("java.awt.headless", "false");`

In order to let the app access to the computer devices.
The issue was actually due to the fact that we moved to a more recent version of JavaFX.

The recording seems to work, before this issue the video was displayed on stat context right ?

**Comment by Tohaker** [comment]
Has this issue been resolved with that PR?

**Comment by kuhlkrein** [comment]
It seems that now the video is saved in the stats folder yes, but we still have to propose it to the user at the end of a game, on the stats page
