### ISSUE TITLE
new games : Discovery shape Games

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#939]

**Comment by kuhlkrein** [comment]
Easy level:

![image](https://user-images.githubusercontent.com/24478346/72157325-ef987800-33b7-11ea-987a-6d8615eeab36.png)


Hard level:

![image](https://user-images.githubusercontent.com/24478346/72157296-ddb6d500-33b7-11ea-8c53-2cbded20cb49.png)

Something like this ?
