### ISSUE TITLE
Tug Of War Game ( Ribbit Race Variant) [NEW GAME]

### ISSUE THREAD

**Issue by Sannaraek** [GazePlay/GazePlay#942]
The user is put up against another user (A biboule with a muscular body may be, would be funny to see).
There is a strength gauge.
The player must target biboulles to fill up the strength gauge.
There is a middle threshold on the strength gauge. If the player reaches above that threshold, the rope is pulled towards the player's side. Works vice versa for the computer opponent.
The strength gauge is always gradually decreasing so the player must constantly replenish his/her strength.
The loser falls in a pond after a certain distance is moved.

**Comment by schwabdidier** [comment]
Funny !
