### ISSUE TITLE
Color game: add more drawings

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#944]
Idea from an Orthoptist:
The drawings for color game have to be specific drawings with "closed lines". It can be hard to find for some people so we should add a few more default drawings like the current dolphin one.

**Comment by kuhlkrein** [comment]
We can find a lot here for example: 

https://www.hugolescargot.com/coloriages/coloriage-en-ligne/

here:

https://coloriage.info

or even here:

https://www.teteamodeler.com/coloriages.asp

**Comment by Yaniissou** [comment]
https://github.com/GazePlay/GazePlay/pull/1720
