### ISSUE TITLE
No sound on windows 10 on release version

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#945]
I have no background music in gazeplay homepage and games and no sound in general in all the games

Tested with ASUS PC Portable convertible tactile

**Comment by kuhlkrein** [comment]
I just retried at home and actually some sounds worked, like the pianosight. I think it's mailny because pianosight uses a synthetisor, while other games are playing mp3 or wav tracks

**Comment by Tohaker** [comment]
There is some work being done on the Resources that should fix this. Some sounds aren't being found by the program if they're in the data folder. Its weird but solvable.

**Comment by Tohaker** [comment]
@kuhlkrein I believe these issues will now be fixed in the latest `master`

**Comment by schwabdidier** [comment]
We will check it next week

**Comment by Tohaker** [comment]
I've not heard any complaints regarding this so I assume its all fixed
