### ISSUE TITLE
Music volume does'nt change on main screen

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#956]

**Comment by kuhlkrein** [comment]
Ok, Actually, when I press play on the home button no music plays, it start to play only when I'm going to config menu, and after that I can't change the volume

**Comment by kuhlkrein** [comment]
music volume should be fixed by #966

**Comment by kuhlkrein** [comment]
It is not fixed, actually the volume will change if we press pause then play, but it is not dynamically changing when we move the slider

**Comment by Tohaker** [comment]
I've just tried this myself and I can't change the volume without actually setting it and restarting the whole app, because the value is only written to the file and not bound to any actual volume link in the MediaPlayer. 
I've got this working locally, will raise a PR over the weekend.

**Comment by Tohaker** [comment]
@kuhlkrein This should be resolved now, feel free to try it on `master`
