### ISSUE TITLE
Effect Volume for some Wav files

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#973]
Effects Volume doesn't change the frod sound + the score is not a the good place on the screen

**Comment by kuhlkrein** [comment]
For some wav files it seems that javaFX have some playing issues, here we can hear the begining of the sound for few milliseconds at a normal volume (system volume) before the volume turns to the effect volume property value.

**Comment by schwabdidier** [comment]
here ?

**Comment by kuhlkrein** [comment]
> here ?

in Frog Game

**Comment by YannRobert** [comment]
wav files are bigger in storage size
IMO there is no point on using this file format, at least for sounds provided in the gazeplay distribution
they better be encoded in mp3 to reduce the size of the gazeplay distribution

**Comment by kuhlkrein** [comment]
Yes, I agree, we should also think about checking the image files to reduce the size of the ones that don't need to have hight definition.
