### ISSUE TITLE
"System" theme is not showing well (seen on Windows)

### ISSUE THREAD

**Issue by YannRobert** [GazePlay/GazePlay#979]
When selecting the "System" UI theme,
the UI is looking very bad, text are unreadable, among other things

See screenshot of game list screen

![image](https://user-images.githubusercontent.com/1653590/71557155-840eec00-2a42-11ea-9b76-6e66e0a6be9c.png)

**Comment by schwabdidier** [comment]
In this theme, there is no associated css. On macOS, I obtain the same thing. Maybe, it would be better to comment this line...

`public enum BuiltInUiTheme {

    SYSTEM("System", null),

    ORANGE("Orange", "main-orange.css"),
`
