### ISSUE TITLE
Promote "Silver and Gold" as default UI Theme (instead of "Green") ?

### ISSUE THREAD

**Issue by YannRobert** [GazePlay/GazePlay#980]
The current default theme is the "Green" UI Theme

![image](https://user-images.githubusercontent.com/1653590/71557242-d1d82400-2a43-11ea-982b-69c734a8de59.png)

The "Silver and Gold" UI Theme is probably, in my opinion, the most classic looking UI Theme available.
That would probably fit the taste of the majority of users

![image](https://user-images.githubusercontent.com/1653590/71557230-87ef3e00-2a43-11ea-8442-d621f1c5385d.png)

Don't you think the default UI Theme should be the most classic?

The "System" theme is broken (see issue #979) and should be fixed.

In the meanwhile, promote the "Silver and Gold" theme as the default.

Eventually, an alternative classic theme can be created to address that?

**Comment by schwabdidier** [comment]
Yes, I am agree with you. If I am not wrong, I did all the themes and they are not very beautiful...

I choose the green theme because I thought it was childish but we can certainly have better colors as default.
