### ISSUE TITLE
[Bug] Buttons are hidden on Tobii I-12 in fullscreen mode.

### ISSUE THREAD

**Issue by Tohaker** [GazePlay/GazePlay#987]
A user has shown me that after playing a game they can't see the Home button on the Stats menu: 
![image](https://user-images.githubusercontent.com/33665681/71749865-8fad4900-2e6e-11ea-80c1-781c82f7b072.png)
They end up in a soft-lock state unless they have a keyboard and can minimise the window.

**Comment by schwabdidier** [comment]
I think it is resolved next release (issue #907).

**Comment by Tohaker** [comment]
Ok thanks, I'll close this and keep an eye on #907
