### ISSUE TITLE
Problem in where it is game

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#994]
Problem of untranslated questions (tested on english and french)

![Capture d’écran de 2020-01-06 13-44-38](https://user-images.githubusercontent.com/24478346/71819037-02930b80-308b-11ea-895b-8ddd624d3553.png)

**Comment by kuhlkrein** [comment]
Hi @Tohaker , I guess it's maybe due to the new ressource location ?

**Comment by kuhlkrein** [comment]
Due to accessing the folderName by: 

```
String folder = (String) resourcesFolders.toArray()[(index) % filesCount];
String[] bits = folder.split("\\\\");
String folderName = bits[bits.length - 1];
```
Does not work on windows, I think we should better use 

`folderName = (new File(folder)).getName();`

to make it work with any OS. (works fine with this implementation on Windows)

**Comment by Tohaker** [comment]
Very strange, it worked for me in testing. But yes this is a better way of finding the name - good spot

**Comment by kuhlkrein** [comment]
I was on linux sorry, not windows :)

**Comment by Tohaker** [comment]
Can this be closed then?

**Comment by schwabdidier** [comment]
When it is done, no ?

**Comment by Tohaker** [comment]
Ah my mistake, I saw the commit but didn't see it was on @kuhlkrein 's own fork.
