### ISSUE TITLE
SpaceGame

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#995]
There is a lot of unused code in the SpaceGame files (especially SpaceGame.java), we should think about cleaning it

**Comment by Tohaker** [comment]
Its all a lot of commented code, which really shouldn't be commited unless there is an explanation why we should keep it. Are there any objections to deleting the commented code?

**Comment by kuhlkrein** [comment]
@Tohaker also lots of functions like the _computeBullet..._ and all the _boss_ related functions are never called in the code... (so we can never fight the boss btw). I would like to have a look at these parts to see if there is a way to make the game work better. 

But for the commented code, I think we can delete it for sure.
